export class DatosModel {
    idFinalista = '';
    codigo = null;
    cerrado: boolean;
    nombreInstitucionEducativa = '';
    direccionInstitucionEducativa = '';
    lugarInstitucionEducativa = '';
    distritoInstitucionEducativa = '';
    provinciaInstitucionEducativa = '';
    regionInstitucionEducativa = '';
    telefonoInstitucionEducativa = '';
    faxInstitucionEducativa = '';
    emailInstitucionEducativa = '';
    publicaPrivada = '';
    nombreDirector = '';
    categoriaC = '';
    categoriaD = '';
    tituloTrabajo = '';
    nombreEstudiante1 = '';
    direccionEstudiante1 = '';
    lugarEstudiante1 = '';
    distritoEstudiante1 = '';
    provinciaEstudiante1 = '';
    regionEstudiante1 = '';
    telefonoEstudiante1 = '';
    emailEstudiante1 = '';
    fechaNacimientoEstudiante1 = '';
    dniEstudiante1 = '';
    gradoEstudiosEstudiante1 = '';
    nombreEstudiante2 = '';
    direccionEstudiante2 = '';
    lugarEstudiante2 = '';
    distritoEstudiante2 = '';
    provinciaEstudiante2 = '';
    regionEstudiante2 = '';
    telefonoEstudiante2 = '';
    emailEstudiante2 = '';
    fechaNacimientoEstudiante2 = '';
    dniEstudiante2 = '';
    gradoEstudiosEstudiante2 = '';
    nombreDocente = '';
    direccionDocente = '';
    lugarDocente = '';
    distritoDocente = '';
    provinciaDocente = '';
    regionDocente = '';
    telefonoDocente = '';
    emailDocente = '';
    fechaNacimientoDocente = '';
    dniDocente = '';
    especialidadDocente = '';
    codigoModularDocente = '';
    cargoDocente = '';
    cursoDocente = '';
    estudiosDocente = '';
    gradosDocente = '';
    institutoUniversidad = '';
    titulado = '';
    maestria = '';
    doctorado = '';

    constructor() {
        this.cerrado = false;
    }
}
